stages:
  - build
  - test
  - analyze
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_HOST_URL: "https://sonarcloud.io"
  SONAR_SCANNER_OPTS: "-Dsonar.projectKey=Gloriantt_PaymentSystem"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn -B -DskipTests clean package

test:
  stage: test
  script:
    - mvn -B test

sonarqube:
  stage: analyze
  script:
    - mvn -B sonar:sonar -Dsonar.login=$SONAR_TOKEN
  only:
    - main

docker-build:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
